//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carfinance.Phoenix.Kata.Angular
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int BookingId { get; set; }
        public Nullable<int> TableNumber { get; set; }
        public string ContactName { get; set; }
        public string ContactNumber { get; set; }
        public Nullable<int> NumberOfPeople { get; set; }
        public Nullable<System.DateTime> BookingTime { get; set; }
    }
}
